// Catalogue de séances route — cadrage produit Section 4 (types de séances)
// et doc technique Section 4. Plusieurs variantes par type pour casser la
// monotonie du plan. `phases` = phases de macrocycle où la séance est éligible.

export const SESSIONS_ROUTE = [
  {
    id: "route_e_footing",
    type: "E",
    zone: "E",
    label: "Footing fondamental",
    phases: ["base", "developpement", "affutage"],
    structure: [{ bloc: "corps", zone: "E", description: "Footing continu allure E" }],
  },
  {
    id: "route_e_vallonne",
    type: "E",
    zone: "E",
    label: "Footing vallonné",
    phases: ["base", "developpement"],
    structure: [{ bloc: "corps", zone: "E", description: "Footing sur parcours vallonné, allure E au ressenti" }],
  },
  {
    id: "route_e_progressif",
    type: "E",
    zone: "E",
    label: "Footing progressif",
    phases: ["base", "developpement"],
    structure: [
      { bloc: "corps_1", zone: "E", description: "2/3 du volume en allure E facile" },
      { bloc: "corps_2", zone: "M", description: "1/3 final en accélérant vers allure M" },
    ],
  },
  {
    id: "route_e_fartlek_libre",
    type: "E",
    zone: "E",
    label: "Footing fartlek libre",
    phases: ["base", "developpement"],
    structure: [{ bloc: "corps", zone: "E", description: "Footing continu avec 4-6 accélérations spontanées non chronométrées, retour libre en allure E" }],
  },
  {
    id: "route_e_cotes_legeres",
    type: "E",
    zone: "E",
    label: "Footing avec côtes légères",
    phases: ["base", "developpement"],
    structure: [{ bloc: "corps", zone: "E", description: "Footing allure E intégrant quelques côtes courtes au fil du parcours, sans forcer l'allure en montée" }],
  },
  {
    id: "route_longue_standard",
    type: "longue",
    zone: "E",
    label: "Sortie longue",
    phases: ["base", "developpement"],
    structure: [{ bloc: "corps", zone: "E", description: "Sortie longue continue, allure E" }],
  },
  {
    id: "route_longue_allure_marathon",
    type: "longue",
    zone: "M",
    label: "Sortie longue avec finish allure M",
    phases: ["developpement", "affutage"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "1h à 1h30 en allure E" },
      { bloc: "corps", zone: "M", description: "20-40 min finale en allure M" },
    ],
  },
  {
    id: "route_longue_progressive",
    type: "longue",
    zone: "E",
    label: "Sortie longue progressive",
    phases: ["base", "developpement"],
    structure: [
      { bloc: "corps_1", zone: "E", description: "Première moitié en allure E facile" },
      { bloc: "corps_2", zone: "E", description: "Seconde moitié en accélérant progressivement, sans dépasser allure M" },
    ],
  },
  {
    id: "route_longue_vallonnee",
    type: "longue",
    zone: "E",
    label: "Sortie longue vallonnée",
    phases: ["base", "developpement"],
    structure: [{ bloc: "corps", zone: "E", description: "Sortie longue sur parcours vallonné, allure E au ressenti" }],
  },
  {
    id: "route_longue_fractionnee",
    type: "longue",
    zone: "M",
    label: "Sortie longue avec fractionné intégré",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "30-40 min allure E" },
      { bloc: "corps", zone: "M", description: "3 x 10-15 min allure M, récup 5 min trot entre les blocs" },
      { bloc: "retour_calme", zone: "E", description: "20-30 min allure E" },
    ],
  },
  {
    id: "route_longue_ravitaillement",
    type: "longue",
    zone: "E",
    label: "Sortie longue avec ravitaillement type course",
    phases: ["developpement", "affutage"],
    structure: [{ bloc: "corps", zone: "E", description: "Sortie longue continue, allure E, avec test du plan de ravitaillement/hydratation de course (gels, boisson)" }],
  },
  {
    id: "route_seuil_continu",
    type: "T",
    zone: "T",
    label: "Seuil continu (tempo)",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "15-20 min" },
      { bloc: "corps", zone: "T", description: "20-40 min continu allure T" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "route_seuil_cruise",
    type: "T",
    zone: "T",
    label: "Cruise intervals (seuil fractionné)",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "15-20 min" },
      { bloc: "corps", zone: "T", description: "4-6 x 1200-1600 m allure T, récup 1 min trot" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "route_seuil_progressif",
    type: "T",
    zone: "T",
    label: "Tempo progressif",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "15 min" },
      { bloc: "corps", zone: "T", description: "25-30 min continu, allure démarrant à E+ et progressant vers T" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "route_seuil_2x20",
    type: "T",
    zone: "T",
    label: "Seuil en 2 blocs de 20 min",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "15-20 min" },
      { bloc: "corps", zone: "T", description: "2 x 20 min allure T, récup 3 min trot entre les blocs" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "route_seuil_alterne",
    type: "T",
    zone: "T",
    label: "Seuil alterné rapide/lent",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "15-20 min" },
      { bloc: "corps", zone: "T", description: "20-25 min en alternant 3 min allure T / 1 min allure E, sans arrêt" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "route_intervalles_vo2",
    type: "I",
    zone: "I",
    label: "Intervalles VO2max",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min + gammes" },
      { bloc: "corps", zone: "I", description: "5-8 x 800-1000 m allure I, récup complète (trot égal au temps d'effort)" },
      { bloc: "retour_calme", zone: "E", description: "10-15 min" },
    ],
  },
  {
    id: "route_intervalles_courts",
    type: "I",
    zone: "I",
    label: "Intervalles courts VO2max",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min + gammes" },
      { bloc: "corps", zone: "I", description: "10-12 x 400 m allure I, récup 200 m trot" },
      { bloc: "retour_calme", zone: "E", description: "10-15 min" },
    ],
  },
  {
    id: "route_intervalles_longs",
    type: "I",
    zone: "I",
    label: "Intervalles longs VO2max",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min + gammes" },
      { bloc: "corps", zone: "I", description: "3-5 x 1200-1600 m allure I, récup trot 3-4 min" },
      { bloc: "retour_calme", zone: "E", description: "10-15 min" },
    ],
  },
  {
    id: "route_intervalles_pyramide",
    type: "I",
    zone: "I",
    label: "Pyramide VO2max",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min + gammes" },
      { bloc: "corps", zone: "I", description: "400-800-1200-800-400 m allure I, récup trot égale au temps d'effort" },
      { bloc: "retour_calme", zone: "E", description: "10-15 min" },
    ],
  },
  {
    id: "route_intervalles_30_30",
    type: "I",
    zone: "I",
    label: "30/30 haute intensité",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min + gammes" },
      { bloc: "corps", zone: "I", description: "2-3 séries de 8-10 x 30s allure I / 30s trot très lent, récup 3 min entre séries" },
      { bloc: "retour_calme", zone: "E", description: "10-15 min" },
    ],
  },
  {
    id: "route_repetitions_vitesse",
    type: "R",
    zone: "R",
    label: "Répétitions vitesse/économie",
    phases: ["base", "developpement", "affutage"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min + gammes + lignes droites" },
      { bloc: "corps", zone: "R", description: "8-12 x 200 m allure R, récup complète marchée" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "route_repetitions_cotes",
    type: "R",
    zone: "R",
    label: "Répétitions côtes courtes",
    phases: ["base", "developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min" },
      { bloc: "corps", zone: "R", description: "8-10 x côte 15-20s effort maximal, récup descente marchée" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "route_repetitions_400",
    type: "R",
    zone: "R",
    label: "Répétitions 400 m",
    phases: ["base", "developpement", "affutage"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min + gammes + lignes droites" },
      { bloc: "corps", zone: "R", description: "6-10 x 400 m allure R, récup complète trottée/marchée" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "route_repetitions_progressives_100",
    type: "R",
    zone: "R",
    label: "Accélérations progressives 100 m",
    phases: ["base", "developpement", "affutage"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min + gammes" },
      { bloc: "corps", zone: "R", description: "8-10 x 100 m en accélération progressive (75%→95% de l'effort), retour marché" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "route_repetitions_300",
    type: "R",
    zone: "R",
    label: "Répétitions 300 m",
    phases: ["developpement"],
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min + gammes + lignes droites" },
      { bloc: "corps", zone: "R", description: "6-8 x 300 m allure R, récup complète 3-4 min trot/marche" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "route_footing_recuperation",
    type: "recuperation",
    zone: "E",
    label: "Footing de récupération",
    phases: ["base", "developpement", "affutage"],
    structure: [{ bloc: "corps", zone: "E", description: "20-35 min très facile, plus court qu'un footing E standard" }],
  },
  {
    id: "route_recuperation_alternee",
    type: "recuperation",
    zone: "E",
    label: "Footing de récupération avec marche",
    phases: ["base", "developpement", "affutage"],
    structure: [{ bloc: "corps", zone: "E", description: "15-25 min très facile, alternance course/marche possible" }],
  },
  {
    id: "route_recuperation_active",
    type: "recuperation",
    zone: "E",
    label: "Décrassage actif",
    phases: ["developpement", "affutage"],
    structure: [{ bloc: "corps", zone: "E", description: "20-30 min très facile, quelques accélérations courtes (foulées) en fin" }],
  },
  {
    id: "route_recuperation_marche_rapide",
    type: "recuperation",
    zone: "E",
    label: "Marche active de récupération",
    phases: ["base", "developpement", "affutage"],
    structure: [{ bloc: "corps", zone: "E", description: "30-40 min de marche rapide, alternative sans impact après une séance exigeante" }],
  },
  {
    id: "route_recuperation_courte_post_qualite",
    type: "recuperation",
    zone: "E",
    label: "Footing très court post-séance de qualité",
    phases: ["developpement"],
    structure: [{ bloc: "corps", zone: "E", description: "15-20 min très facile le lendemain d'une séance de qualité, uniquement pour favoriser la circulation" }],
  },
];
