// Catalogue de séances trail — variantes route Section 4 adaptées au
// dénivelé (D+/D-). `elevationTag` indique le profil attendu.

export const SESSIONS_TRAIL = [
  {
    id: "trail_e_nature",
    type: "E",
    zone: "E",
    label: "Footing nature",
    phases: ["base", "developpement", "affutage"],
    elevationTag: "leger",
    structure: [{ bloc: "corps", zone: "E", description: "Footing sur sentier, D+ modéré, allure E au GAP" }],
  },
  {
    id: "trail_e_denivele",
    type: "E",
    zone: "E",
    label: "Footing avec dénivelé soutenu",
    phases: ["developpement"],
    elevationTag: "soutenu",
    structure: [{ bloc: "corps", zone: "E", description: "Sortie vallonnée, D+ significatif, allure au ressenti (GAP)" }],
  },
  {
    id: "trail_longue_denivele_progressif",
    type: "longue",
    zone: "E",
    label: "Sortie longue D+ progressif",
    phases: ["base", "developpement"],
    elevationTag: "progressif",
    structure: [{ bloc: "corps", zone: "E", description: "Sortie longue, D+ cumulé croissant sur le cycle" }],
  },
  {
    id: "trail_longue_specifique",
    type: "longue",
    zone: "M",
    label: "Sortie longue spécifique objectif",
    phases: ["developpement", "affutage"],
    elevationTag: "specifique",
    structure: [{ bloc: "corps", zone: "M", description: "Profil et D+ proches de la course cible" }],
  },
  {
    id: "trail_seuil_cotes_longues",
    type: "T",
    zone: "T",
    label: "Seuil en côtes longues",
    phases: ["developpement"],
    elevationTag: "soutenu",
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min" },
      { bloc: "corps", zone: "T", description: "3-4 x 8-10 min montée continue à allure T (effort), récup descente facile" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "trail_intervalles_cotes",
    type: "I",
    zone: "I",
    label: "Intervalles en côtes",
    phases: ["developpement"],
    elevationTag: "soutenu",
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min" },
      { bloc: "corps", zone: "I", description: "6-8 x 3-4 min montée effort I, récup descente trot" },
      { bloc: "retour_calme", zone: "E", description: "10-15 min" },
    ],
  },
  {
    id: "trail_repetitions_descente",
    type: "R",
    zone: "R",
    label: "Répétitions techniques de descente",
    phases: ["developpement", "affutage"],
    elevationTag: "descente",
    structure: [
      { bloc: "echauffement", zone: "E", description: "20 min" },
      { bloc: "corps", zone: "R", description: "6-8 x descente technique 1-2 min, remontée facile en récup" },
      { bloc: "retour_calme", zone: "E", description: "10 min" },
    ],
  },
  {
    id: "trail_footing_recuperation",
    type: "recuperation",
    zone: "E",
    label: "Footing de récupération nature",
    phases: ["base", "developpement", "affutage"],
    elevationTag: "plat",
    structure: [{ bloc: "corps", zone: "E", description: "20-35 min terrain roulant, D+ minimal" }],
  },
];
